export default html(() => {
  const features = [
    { icon: '🚀', title: 'Zero Config', desc: 'Runs directly in Bun without a build step.' },
    { icon: '🛡️', title: 'Type Safe', desc: 'Full TypeScript support for props and elements.' },
    { icon: '⚡', title: 'Blazing Fast', desc: 'Compiled to a high-performance string builder.' },
  ];

  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Server-Side TSX ⚛️</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700;900&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="/styles/counter.css" />
      </head>
      <body>
        <main class="container">
          <header class="hero">
            <div class="logo-wrapper">
              <span class="logo-emoji">⚛️</span>
            </div>
            <h1 class="gradient-text">TSX Rendering</h1>
            <p class="subtitle">Beautiful, server-rendered HTML using TSX, right out of the box.</p>
          </header>

          <div class="card-grid">
            <section class="card glass-effect" style="grid-column: 1 / -1;">
              <div class="card-header">
                <span class="card-icon">🧠</span>
                <h2>It's Just Functions</h2>
              </div>
              <p class="card-desc">
                This entire page is generated by a single function in <code>jsx.tsx</code>. 
                You get the full power of TypeScript, variables, loops, and conditional rendering, 
                all resolved on the server before it reaches the browser!
              </p>
              
              <ul style="margin: 1.5rem 0; padding-left: 1.5rem; color: #a1a1aa; line-height: 1.6;">
                {features.map((f) => (
                  <li>
                    <strong>{f.icon} {f.title}:</strong> {f.desc}
                  </li>
                ))}
              </ul>
              
              <div style="margin-top: 1.5rem; display: flex; gap: 1rem;">
                <a href="/" class="secondary-btn">
                  ← Back to Home
                </a>
              </div>
            </section>
          </div>
        </main>
      </body>
    </html>
  );
});
